spring.application.name=ms-conta

# =========================
# WRITE DATABASE
# =========================

spring.datasource.write.url=jdbc:postgresql://postgres:5432/bantads
spring.datasource.write.username=postgres
spring.datasource.write.password=postgres
spring.datasource.write.driver-class-name=org.postgresql.Driver

# Schema padr�o do WRITE
spring.jpa.properties.hibernate.default_schema=conta_write

# =========================
# READ DATABASE
# =========================

spring.datasource.read.url=jdbc:postgresql://postgres:5432/bantads
spring.datasource.read.username=postgres
spring.datasource.read.password=postgres
spring.datasource.read.driver-class-name=org.postgresql.Driver

# Schema padr�o do READ (se voc� tiver EntityManager separado, melhor ainda configurar nele)
# spring.jpa.properties.hibernate.default_schema=conta_read

# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# RABBITMQ
# =========================

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest