version: '3.8'

services:
  mongo_db: 
    image: mongo:latest
    container_name: mongo_auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ms_auth: 
    build: 
      context: ./ms_auth
      dockerfile: Dockerfile
    container_name: ms_auth
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/auth_db
    depends_on:
      - mongo_db
  
volumes: 
  mongo_data:

