version: '3.8'

services:
  mongo_db: 
    image: mongo:latest
    container_name: mongo_auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  db_cliente:
    image: postgres:15-alpine
    container_name: db_cliente
    environment:
      POSTGRES_DB: cliente_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ms_auth: 
    build: 
      context: ./ms_auth
      dockerfile: Dockerfile
    container_name: ms_auth
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_db:27017/auth_db
    depends_on:
      - mongo_db

  ms_cliente: 
    build: 
      context: ./ms-cliente
      dockerfile: Dockerfile
    container_name: ms_cliente
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_cliente:5432/cliente_db
    depends_on:
      - db_cliente
  
volumes: 
  mongo_data:

