spring.application.name=ms-gerente

spring.datasource.url=jdbc:postgresql://localhost:5432/bantads_gerente
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.default_schema=gerente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

server.port=8080